### ISSUE TITLE
Social auth does not handle exceptions correctly

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#270]
WHen logging in using gmail this afternoon I got this error (see below)
The error is "gmail account already in use". This should show me some message, not crash the server. 

ERROR 2014-02-17 15:37:54,685 base 5868 140596481005376 Internal Server Error: /socialauth/complete/google/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/decorators.py", line 37, in wrapper
    return func(request, backend, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/views.py", line 37, in complete
    return associate_complete(request, backend, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/views.py", line 47, in associate_complete
    user = auth_complete(request, backend, request.user, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/views.py", line 170, in auth_complete
    return backend.auth_complete(user=user, request=request, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/backends/__init__.py", line 469, in auth_complete
    return authenticate(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/**init**.py", line 59, in authenticate
    user = backend.authenticate(*_credentials)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/backends/**init**.py", line 110, in authenticate
    out = self.pipeline(pipeline, *args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/backends/**init**.py", line 144, in pipeline
    result = func(_args, *_out) or {}
  File "/usr/local/lib/python2.7/dist-packages/social_auth/backends/pipeline/social.py", line 20, in social_auth_user
    raise AuthException(backend, msg % {'provider': backend.name})
AuthException: This google account already in use.

**Comment by jmsmkn** [comment]
fixed
